name: release-puppeteer

on:
  push:
    branches: [release/docker-push]

env:
  _appName: puppeteer-api
  _repoName: fangqk1991/puppeteer-api
  _dockerFile: ./deploy/puppeteer/Dockerfile

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push
        run: |
          # docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          commitSHA=${GITHUB_SHA::8}
          latestImageTag="$_repoName:$commitSHA"
          docker buildx build --platform linux/arm64,linux/amd64 -t $_repoName -t $latestImageTag -f $_dockerFile . --build-arg "commitSHA=$commitSHA" --push

      - name: Bot
        run: |
          message="$_appName ${GITHUB_SHA::8} pushed."
          curl -X POST "${{secrets.TG_BOT_URL}}" -H 'Content-Type: application/json' -d "{\"text\":\"$message\"}"
